"""
generate_report.py — Generate a structured radiology report using an LLM.

Features:
1. Gathers predicted findings and retrieved evidence.
2. Formats messages for OpenAI API.
3. Enforces RadiologyReport pydantic schema.
4. Includes retry logic for invalid JSON.
"""

import os
import json
import yaml
import logging
from typing import Dict, List, Any
from openai import OpenAI
from dotenv import load_dotenv

# Load environment variables
load_dotenv()
from src.api.schemas import RadiologyReport
from src.generation.prompts import SYSTEM_PROMPT, USER_PROMPT_TEMPLATE, format_findings, format_evidence

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)

class ReportGenerator:
    """Handles interaction with the LLM for report generation."""
    
    def __init__(self, model_name: str = "gpt-4o"):
        self.model_name = model_name
        self.client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY"))
        
    def generate(self, predictions: Dict[str, float], hits: List[Dict[str, Any]], 
                 top_k: int = 5, threshold: float = 0.4) -> RadiologyReport:
        """Generates a structured report with retries."""
        
        # 1. Format Prompt
        findings_str = format_findings(predictions, threshold=threshold)
        evidence_str = format_evidence(hits[:top_k])
        
        user_content = USER_PROMPT_TEMPLATE.format(
            findings_list=findings_str,
            top_k=top_k,
            evidence_chunks=evidence_str
        )
        
        messages = [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_content}
        ]
        
        # 2. Call LLM with Retries
        for attempt in range(2):
            try:
                logger.info(f"Generating report (Attempt {attempt + 1})...")
                response = self.client.chat.completions.create(
                    model=self.model_name,
                    messages=messages,
                    response_format={"type": "json_object"},
                    temperature=0.0 # Greedy for determinism
                )
                
                # 3. Parse and Validate
                raw_content = response.choices[0].message.content
                # Strip markdown fences if present
                clean_json = raw_content.strip().removeprefix("```json").removesuffix("```").strip()
                
                return RadiologyReport.model_validate_json(clean_json)
                
            except Exception as e:
                logger.warning(f"Generation attempt {attempt + 1} failed: {e}")
                continue
                
        # 4. Fallback
        logger.error("All generation attempts failed. Returning fallback report.")
        return RadiologyReport(
            findings="Automated generation failed. Please review images and raw evidence directly.",
            impression="Generation Error",
            rationale="LLM failed to produce valid JSON after 2 attempts.",
            caution="TECHNICAL ERROR: REPORT NOT GENERATED BY MODEL.",
            escalate=True,
            confidence="low"
        )

if __name__ == "__main__":
    # Mock test (requires OPENAI_API_KEY)
    if not os.environ.get("OPENAI_API_KEY"):
        logger.warning("OPENAI_API_KEY not found. Skipping live test.")
    else:
        gen = ReportGenerator()
        mock_preds = {"cardiomegaly": 0.85, "effusion": 0.12, "edema": 0.77}
        mock_hits = [
            {"study_id": "123", "chunk_text": "Heart size is enlarged.", "section": "findings"},
            {"study_id": "456", "chunk_text": "Mild pulmonary vascular congestion.", "section": "impression"}
        ]
        
        report = gen.generate(mock_preds, mock_hits)
        print("\nGenerated Report:")
        print(report.model_dump_json(indent=2))
