"""
schemas.py — Pydantic models for RadReason API and generation.
"""

from pydantic import BaseModel, Field
from typing import List, Literal, Optional

class RadiologyReport(BaseModel):
    """Structured radiology report generated by the LLM."""
    findings: str = Field(..., description="Detailed findings based on image and evidence.")
    impression: str = Field(..., description="Clinical impression/conclusion.")
    rationale: str = Field(..., description="Reasoning linking evidence to findings.")
    caution: str = Field(..., description="Warning about model limitations.")
    escalate: bool = Field(..., description="True if human review is critically needed.")
    confidence: Literal["high", "moderate", "low"] = Field(..., description="Self-assessed confidence level.")

class Prediction(BaseModel):
    label: str
    prob: float

class RetrievalResult(BaseModel):
    chunk_id: str
    text: str
    score: float
    study_id: str

class ReportRequest(BaseModel):
    image_path: str
    clinical_indication: Optional[str] = None

class ReportResponse(BaseModel):
    predictions: List[Prediction]
    retrieved_evidence: List[RetrievalResult]
    summary: RadiologyReport
